admin_tableaudebord:
    path:     /tableaudebord/{structureId}
    defaults: { _controller: "BalancelleBundle:Admin:tableauDeBord", structureId: null }
    methods:  GET

admin_initialisernouvelleannee:
    path:     /initialiser/{etape}
    defaults: { _controller: "BalancelleBundle:Admin:initialiserNouvelleAnnee", etape: null }
    methods:  [GET]

admin_etapeChangementAnnee:
    path:     /etapeChangementAnnee
    defaults: { _controller: "BalancelleBundle:Admin:etapeChangementAnnee" }
    methods:  [GET,POST]

admin_etapeGestionDesFamilles:
    path:     /etapeGestionDesFamilles
    defaults: { _controller: "BalancelleBundle:Admin:etapeGestionDesFamilles" }
    methods:  [GET,POST]

admin_purgerAnneeAnterieure:
    path: /purger
    defaults: { _controller: "BalancelleBundle:Admin:purgerAnneeAnterieure" }
    methods:  [POST]

admin_etapeFin:
    path:     /etapeFin
    defaults: { _controller: "BalancelleBundle:Admin:etapeFin" }
    methods:  [GET,POST]