famille_tableauDeBord:
    path:     /tableauDeBord
    defaults: { _controller: "BalancelleBundle:Famille:tableauDeBord" }
    methods:  [GET]

famille_erreurFamille:
    path:     /erreurFamille/
    defaults: { _controller: "BalancelleBundle:Famille:erreurFamille" }