permanence_index:
    path:     /planning/{structure}
    defaults: { _controller: "BalancelleBundle:Permanence:index" }
    methods:  GET

permanence_inscription:
    path:     /{id}/inscription
    defaults: { _controller: "BalancelleBundle:Permanence:inscription" }
    methods:  [GET, POST]

permanence_desinscription:
    path:     /desinscription
    defaults: { _controller: "BalancelleBundle:Permanence:desinscription" }
    methods:  [POST]

permanence_echange:
    path:     /echange
    defaults: { _controller: "BalancelleBundle:Permanence:echange" }
    methods:  [POST]

admin_permanence_index:
    path:     /admin
    defaults: { _controller: "BalancelleBundle:Permanence:tableauDeBord" }
    methods:  GET

admin_permanence_structure:
    path:     /admin/structure/{structure}
    defaults: { _controller: "BalancelleBundle:Permanence:indexAdmin" }
    methods:  GET

admin_permanence_ajouterFamille:
    path:     /admin/ajouterFamille
    defaults: { _controller: "BalancelleBundle:Permanence:ajouterFamille" }
    methods:  [POST]

admin_permanence_desinscrireFamille:
    path:     /admin/desinscrireFamille
    defaults: { _controller: "BalancelleBundle:Permanence:desinscrireFamille" }
    methods:  [POST]

admin_permanence_suppression:
    path:     /admin/supprimerPermanence
    defaults: { _controller: "BalancelleBundle:Permanence:supprimerPermanence" }
    methods:  [POST]

admin_permanence_creer:
    path:     /admin/creerPermanence/{semaineId}/{date}
    defaults: { _controller: "BalancelleBundle:Permanence:creerPermanence", semaineId: null, date: null}
    methods:  [GET, POST]