structure_index:
    path:     /
    defaults: { _controller: "BalancelleBundle:Structure:index" }
    methods:  GET

structure_new:
    path:     /new
    defaults: { _controller: "BalancelleBundle:Structure:new" }
    methods:  [GET, POST]

structure_edit:
    path:     /{id}/edit
    defaults: { _controller: "BalancelleBundle:Structure:edit" }
    methods:  [GET, POST]

structure_delete:
    path:     /{id}/delete
    defaults: { _controller: "BalancelleBundle:Structure:delete" }
    methods:  DELETE

structure_envoi_mail:
    path:     /{id}/envoyerMail
    defaults: { _controller: "BalancelleBundle:Structure:envoyerMail" }
    methods:  [GET, POST]
