user_index:
    path:     /
    defaults: { _controller: "BalancelleBundle:User:index" }
    methods:  GET

user_show:
    path:     /{id}/show
    defaults: { _controller: "BalancelleBundle:User:show" }
    methods:  GET

user_new:
    path:     /new
    defaults: { _controller: "BalancelleBundle:User:new" }
    methods:  [GET, POST]

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "BalancelleBundle:User:edit" }
    methods:  [GET, POST]

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "BalancelleBundle:User:delete" }
    methods:  DELETE

user_verifier_mail:
    path:     /verifiermail
    defaults: { _controller: "BalancelleBundle:User:verifiermail" }
    methods:  [POST]