<?php

namespace BalancelleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AnneeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnneeRepository extends EntityRepository
{
    /**
     * Permet de récupérer les familles d'une structure
     * @param int $anneeEnCours - l' année en cours
     * @return int|mixed|string
     */
    public function desactiverLesAnnesNonValide($anneeEnCours)
    {
        $queryBuilder = $this->createQueryBuilder('a');
        $queryBuilder->update()
            ->set('a.active', '0')
            ->where($queryBuilder->expr()->neq('a.annee', $anneeEnCours))
            ->getQuery()
            ->execute();
    }
}
