<?php

namespace BalancelleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EnfantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnfantRepository extends EntityRepository
{
    /**
     * Fonction de recherche d'autocomplétion
     * @param $recherche
     * @return mixed
     */
    public function autocomplete($recherche)
    {
        return $this
            ->createQueryBuilder('a')
            ->andWhere('a.prenom LIKE :recherche')
            ->orWhere('a.nom LIKE :recherche')
            ->setParameter('recherche', "%$recherche%")
            ->orderBy('a.prenom')
            ->getQuery()
            ->execute()
            ;
    }

    /**
     * Récupère les enfants non liés à une famille
     * @return mixed
     */
    public function getEnfantSansFamille()
    {
        return $this
            ->createQueryBuilder('a')
            ->andWhere('a.famille is NULL')
            ->andWhere('a.active = 1')
            ->orderBy('a.prenom')
            ->getQuery()
            ->execute()
            ;
    }
}
