<?php

namespace BalancelleBundle\Repository;

/**
 * FamilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamilleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByFamille($userId)
    {
        return $this
            ->createQueryBuilder('a')
            ->where('a.parent1 = :userId' )
            ->orWhere('a.parent2 = :userId')
            ->setParameter( 'userId', "$userId")
            ->andWhere('a.active = true')
            ->getQuery()
            ->getOneOrNullResult();
    }
}
