<?php

namespace BalancelleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MagasinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MagasinRepository extends EntityRepository
{
    public function getMagasinActive()
    {
        return $this
            ->createQueryBuilder('a')
            ->where('a.active = 1')
            ->getQuery()
            ->execute()
            ;
    }
}
