<?php

namespace BalancelleBundle\Repository;

/**
 * PermanenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PermanenceRepository extends \Doctrine\ORM\EntityRepository
{
    public function recupererLesPermanencesRealisees($famille)
    {
        return $this
            ->createQueryBuilder('p')
            ->where('p.famille = :famille')
            ->andWhere('p.fin < :date')
            ->setParameter('famille', $famille)
            ->setParameter('date', date("Y-m-d H:i:s"))
            ->orderBy('p.debut', 'ASC')
            ->getQuery()
            ->execute();
    }
}
