<?php

namespace BalancelleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PreferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PreferenceRepository extends EntityRepository
{
}
