<?php

namespace BalancelleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SemaineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SemaineRepository extends EntityRepository
{
}
