<?php

namespace BalancelleBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;

/**
 * StructureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StructureRepository extends EntityRepository
{
    /**
     * Récupère les enfants non liés à une famille
     * @return mixed
     */
    public function coutStructure()
    {
        try {
            return $this
                ->createQueryBuilder('a')
                ->select('COUNT(a.id)')
                ->where('a.active = 1')
                ->getQuery()
                ->getSingleScalarResult()
                ;
        } catch (NoResultException $e) {
        } catch (NonUniqueResultException $e) {
        }
    }
}
