<?php

namespace BalancelleBundle\Repository;

use BalancelleBundle\Entity\Structure;
use Doctrine\ORM\EntityRepository;
use BalancelleBundle\Entity\Famille;
use BalancelleBundle\Entity\Enfant;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function filterByRole($role)
    {
        return $this
            ->createQueryBuilder('a')
            ->where('a.roles LIKE :roles')
            ->setParameter('roles', '%"'.$role.'"%')
            ->orderBy('a.prenom')
            ->getQuery()
            ->execute()
            ;
    }

    /** Récupère les utilisateur d'une structure
     * @param Structure $structure
     * @return mixed
     */
    public function recupererLesUtilisateursViaStructure($structure)
    {
        $query = $this
            ->createQueryBuilder('u')
            ->from(Famille::class, 'f')
            ->from(Enfant::class, 'e');
        if ($structure !== null) {
            $query->where('e.structure = :structure');
            $query->setParameter('structure', $structure);
        }
        $query->andWhere('e.famille = f.id')
            ->andWhere('f.parent1 = u.id')
            ->orWhere('f.parent2 = u.id');
        return $query->getQuery()->execute();
    }
}
