<?php

namespace BalancelleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function filterByRole($role)
    {
        return $this
            ->createQueryBuilder('a')
            ->where('a.roles LIKE :roles')
            ->setParameter('roles', '%"'.$role.'"%')
            ->orderBy('a.prenom')
            ->getQuery()
            ->execute()
            ;
    }
}
