<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * RevuepresseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RevuepresseRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllActiveRevuepresse()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT e FROM AppBundle:Revuepresse e WHERE e.active = 1 '
                    . 'ORDER BY e.date ASC'
            )
            ->getResult();
    }
}
