balancelle:
    resource: "@BalancelleBundle/Resources/config/routing.yml"
    prefix:   /balancelle

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
balancelle_user:
    resource: "@BalancelleBundle/Resources/config/routing/user.yml"
    prefix:   /user/admin
 
balancelle_user_enregistrement:
    resource: "@BalancelleBundle/Resources/config/routing/userEnregistrement.yml"
    prefix:   /user/enregistrement
