balancelle:
    resource: "@BalancelleBundle/Resources/config/routing.yml"
    prefix:   /

#app:
#    resource: "@AppBundle/Resources/config/routing.yml"
#    resource: "@BalancelleBundle/Resources/config/routing.yml"
#    prefix:   /
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# config/routes/calendar.yaml
calendar:
    resource: "@CalendarBundle/Resources/config/routing.yaml"

logout:
    path: /logout