# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_PARENT: ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/balancelle/famille, role: ROLE_USER }
        - { path: ^/balancelle/permanence, role: ROLE_USER }
        - { path: ^/balancelle/permanence/admin, role: ROLE_ADMIN }
        - { path: ^/balancelle/user/enregistrement, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/balancelle/contact, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/balancelle/, role: ROLE_USER }
        #- { path: ^/user/admin, role: ROLE_ADMIN }
        #- { path: ^/user/user, role: ROLE_USER }

        #- { path: ^/enfant, role: ROLE_ADMIN }