app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
    
app_trenteans:
    path:   /trenteans
    defaults: { _controller: AppBundle:Default:trenteAns }

app_admin_index:
    path:     /admin
    defaults: { _controller: AppBundle:Admin:index }

app_admin_evenements_liste:
    path:     /admin/evenementsListe
    defaults: { _controller: AppBundle:Admin:evenementsListe }
    
app_admin_evenements_add:
    path:     /admin/evenementsAdd
    defaults: { _controller: AppBundle:Admin:evenementsSave }

app_admin_evenements_modify:
    path:     /admin/evenementsModify/{idevenement}
    defaults: { _controller: AppBundle:Admin:evenementsSave }