app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

app_revuepresse:
    path:   /rp
    defaults: { _controller: AppBundle:Default:revuePresse }
    
app_trenteans:
    path:   /trenteans
    defaults: { _controller: AppBundle:Default:trenteAns }