balancelle_famille:
    resource: "@BalancelleBundle/Resources/config/routing/famille.yml"
    prefix:   /famille

balancelle_famille_admin:
  resource: "@BalancelleBundle/Resources/config/routing/familleAdmin.yml"
  prefix:   /admin/famille

balancelle_user:
    resource: "@BalancelleBundle/Resources/config/routing/user.yml"
    prefix:   /user/admin

balancelle_user_enregistrement:
    resource: "@BalancelleBundle/Resources/config/routing/userEnregistrement.yml"
    prefix:   /user/enregistrement

balancelle_enfant:
    resource: "@BalancelleBundle/Resources/config/routing/enfant.yml"
    prefix:   /enfant

balancelle_permanence:
  resource: "@BalancelleBundle/Resources/config/routing/permanence.yml"
  prefix:   /permanence

balancelle_structure:
  resource: "@BalancelleBundle/Resources/config/routing/structure.yml"
  prefix:   /structure

balancelle_calendrier:
  resource: "@BalancelleBundle/Resources/config/routing/calendrier.yml"
  prefix:   /calendrier

balancelle_magasin:
  resource: "@BalancelleBundle/Resources/config/routing/magasin.yml"
  prefix:   /magasin

balancelle_course:
  resource: "@BalancelleBundle/Resources/config/routing/course.yml"
  prefix:   /course

balancelle_admin:
  resource: "@BalancelleBundle/Resources/config/routing/admin.yml"
  prefix:   /admin

balancelle_preference:
  resource: "@BalancelleBundle/Resources/config/routing/preference.yml"
  prefix:   /preference

balancelle_annee:
  resource: "@BalancelleBundle/Resources/config/routing/annee.yml"
  prefix:   /annee

balancelle_nouvelle_annee:
  resource: "@BalancelleBundle/Resources/config/routing/nouvelleAnnee.yml"
  prefix:   /nouvelleAnnee

balancelle_homepage:
    path:     /
    defaults: { _controller: BalancelleBundle:Default:index }

balancelle_contact:
    path:     /contact
    defaults: { _controller: BalancelleBundle:Default:contact }