balancelle_famille:
    resource: "@BalancelleBundle/Resources/config/routing/famille.yml"
    prefix:   /famille

balancelle_user:
    resource: "@BalancelleBundle/Resources/config/routing/user.yml"
    prefix:   /user/admin

balancelle_user_enregistrement:
    resource: "@BalancelleBundle/Resources/config/routing/userEnregistrement.yml"
    prefix:   /user/enregistrement

balancelle_enfant:
    resource: "@BalancelleBundle/Resources/config/routing/enfant.yml"
    prefix:   /enfant

balancelle_permanence:
  resource: "@BalancelleBundle/Resources/config/routing/permanence.yml"
  prefix:   /permanence

balancelle_structure:
  resource: "@BalancelleBundle/Resources/config/routing/structure.yml"
  prefix:   /structure

balancelle_calendrier:
  resource: "@BalancelleBundle/Resources/config/routing/calendrier.yml"
  prefix:   /calendrier

balancelle_homepage:
    path:     /
    defaults: { _controller: BalancelleBundle:Default:index }
    
balancelle_admin_index:
    path:     /admin
    defaults: { _controller: BalancelleBundle:Admin:index }

balancelle_admin_evenements_liste:
    path:     /admin/evenementsListe
    defaults: { _controller: BalancelleBundle:Admin:evenementsListe }
    
balancelle_admin_evenements_add:
    path:     /admin/evenementsAdd
    defaults: { _controller: BalancelleBundle:Admin:evenementsSave }

balancelle_admin_evenements_modify:
    path:     /admin/evenementsModify/{idevenement}
    defaults: { _controller: BalancelleBundle:Admin:evenementsSave }
    
balancelle_admin_revuepresse_liste:
    path:     /admin/revuepresseListe
    defaults: { _controller: BalancelleBundle:Admin:revuepresseListe }
    
balancelle_admin_revuepresse_add:
    path:     /admin/revuepresseAdd
    defaults: { _controller: BalancelleBundle:Admin:revuepresseSave }

balancelle_admin_revuepresse_modify:
    path:     /admin/revuepresseModify/{idrevuepresse}
    defaults: { _controller: BalancelleBundle:Admin:revuepresseSave }

balancelle_contact:
    path:     /contact
    defaults: { _controller: BalancelleBundle:Default:contact }