services:
  _defaults:
    autowire: true

  BalancelleBundle\EventListener\CalendarListener:
    #arguments: ['@service_container']
    tags:
      - { name: 'kernel.event_listener', event: 'calendar.set_data', method: load }
