services:
  _defaults:
    autowire: true

  BalancelleBundle\EventListener\FullCalendarListener:
    #arguments: ['@service_container']
    tags:
      - { name: 'kernel.event_listener', event: 'fullcalendar.set_data', method: loadEvents }
